version: "3.8"
services:
  band-flask-pro:
    build: .
    image: ${DOCKER_HUB_CREDS_USR}/band-flask-pro:latest
    container_name: band-flask-pro
    environment:
      DATABASE_URI: mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@band-flask-pro-db:3306/bfp
      CREATE_SCHEMA:
      SECRET_KEY:
    ports:
    - target: 5000
      published: 80
  database:
    container_name: band-flask-pro-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: bfp
    volumes:
    - type: volume
      source: database
      target: /var/lib/mysql
volumes:
  database:

